# Site settings
title: My Jekyll Site
description: This is a sample Jekyll site.
baseurl: "" # The base URL of your site (without the trailing slash)
url: "https://https://gtystahl.github.io/ase23/" # The full URL of your site

# Build settings
markdown: kramdown
permalink: pretty

# Default values for new pages and posts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
