name: test
on: [push, workflow_dispatch]
permissions: write-all
jobs:
  test:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ./src/hw1; (python3 script.py -g all) > ../../etc/out/scriptOut.txt; cat ../../etc/out/scriptOut.txt;
      - run: | 
          cd ./src/hw2; (python3 data.py -g all) > ../../etc/out/dataOut.txt; cat ../../etc/out/dataOut.txt;
      - run: | 
          cd ./src/hw3; (python3 cluster.py -g all) > ../../etc/out/clusterOut.txt; cat ../../etc/out/clusterOut.txt;
      - run: | 
          cd ./src/hw4; (python3 grid.py -g all) > ../../etc/out/gridOut.txt; cat ../../etc/out/gridOut.txt;
      - run: | 
          cd ./src/hw4; (python3 grid.py -g Every) > ../../etc/out/task5Out.txt; cat ../../etc/out/task5Out.txt;
      - run: | 
          cd ./src/hw5; (python3 bins.py -g bins) > ../../etc/out/binsOut.txt; cat ../../etc/out/binsOut.txt;
      - run: | 
          cd ./src/hw6; (python3 xpln.py -g xpln) > ../../etc/out/xplnOut.txt; cat ../../etc/out/xplnOut.txt;
      - run: | 
          cd ./src/hw7; (python3 stats.py -g all) > ../../etc/out/statsOut.txt; cat ../../etc/out/statsOut.txt;
      - run: |
          val=$(cat counter.txt)
          echo $(($val + 1)) > counter.txt
          echo ${{github.token}} > token.txt;
          git config --global user.name gtystahl
          git config --global user.email ${{ secrets.SPECIAL_STUFF }}
          gh auth login --with-token < token.txt;
          rm token.txt;
          git add etc/out/*;
          git add counter.txt
          git commit -m "Pushing test outs...";
          git push;
      - run: echo "This job's status is ${{ job.status }}."
