name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ./src/hw1; (python3 script.py -g all) > ../../etc/out/scriptOut.txt
      - run: | 
          cd ./src/hw2; (python3 data.py -g all) > ../../etc/out/dataOut.txt
      - run: echo "This job's status is ${{ job.status }}."
